# jenkins

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-home
  namespace: devops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-client
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: jenkins-home
        # namespace: devops
        persistentVolumeClaim:
          claimName: jenkins-home
      containers:
      - name: jenkins
        image: jenkins/jenkins
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        - name: slavelistener
          containerPort: 50000
          protocol: TCP
        env:  
        - name: JAVA_OPTS
          value: -Dhudson.security.csrf.GlobalCrumbIssuerConfiguration.DISABLE_CSRF_PROTECTION=true

        volumeMounts:
        - name: jenkins-home
          mountPath: /var/jenkins_home

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30180

---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-agent
  namespace: devops
spec:
  selector:
    app: jenkins
  ports:
  - name: slavelistener
    protocol: TCP
    port: 50000
    targetPort: 50000
